"use client";

import ReactMarkdown from "react-markdown";
import { useAnalysisStore } from "@/store/analysisStore";
import { Download } from "lucide-react";
import { palette } from "@/lib/colors";
import { formatWon, formatCount } from "@/lib/formatters";

/** Generate a markdown summary from analysisData since there is no report field */
function generateReport(data: NonNullable<ReturnType<typeof useAnalysisStore.getState>["analysisData"]>): string {
  const lines: string[] = [];

  lines.push("# 상권 분석 리포트\n");

  // Store summary
  const ss = data.store_summary;
  if (ss) {
    lines.push("## 업종 현황");
    lines.push(`- 총 점포 수: **${formatCount(ss.total)}개**`);
    const topCategories = Object.entries(ss.by_category ?? {})
      .sort((a, b) => b[1].count - a[1].count)
      .slice(0, 5);
    if (topCategories.length > 0) {
      lines.push("- 주요 업종: " + topCategories.map(([k, v]) => `${k}(${v.count}개, ${v.ratio.toFixed(1)}%)`).join(", "));
    }
    lines.push("");
  }

  // Sales summary
  const sl = data.sales_summary;
  if (sl) {
    lines.push("## 매출 현황");
    lines.push(`- 총 매출: **${formatWon(sl.total_sales)}**`);
    lines.push(`- 총 건수: **${formatCount(sl.total_count)}건**`);
    if (sl.per_store && sl.per_store.length > 0) {
      const topSales = [...sl.per_store].sort((a, b) => b.점포당_매출 - a.점포당_매출).slice(0, 3);
      lines.push("- 점포당 매출 상위: " + topSales.map((s) => `${s.업종}(${formatWon(s.점포당_매출)})`).join(", "));
    }
    lines.push("");
  }

  // Foot traffic
  const ft = data.ft_summary;
  if (ft) {
    lines.push("## 유동인구");
    lines.push(`- 총 유동인구: **${formatCount(ft.total)}명**`);
    const peakTime = Object.entries(ft.time_slots ?? {}).sort((a, b) => b[1] - a[1])[0];
    if (peakTime) {
      lines.push(`- 피크 시간대: **${peakTime[0]}** (${formatCount(peakTime[1])}명)`);
    }
    const peakAge = Object.entries(ft.by_age ?? {}).sort((a, b) => b[1] - a[1])[0];
    if (peakAge) {
      lines.push(`- 주요 연령대: **${peakAge[0]}** (${formatCount(peakAge[1])}명)`);
    }
    lines.push("");
  }

  // Population
  const pop = data.pop_summary;
  if (pop) {
    lines.push("## 상주인구");
    lines.push(`- 총 인구: **${formatCount(pop.total)}명** (${formatCount(pop.households)} 세대)`);
    lines.push("");
  }

  // Opportunities
  const opp = data.opportunities;
  if (opp?.insights) {
    lines.push("## 기회 분석");
    lines.push(`- 활력도: **${opp.insights.vitality}**`);
    lines.push(`- 개업: ${opp.insights.open_count}개 / 폐업: ${opp.insights.close_count}개`);
    if (opp.recommendations && opp.recommendations.length > 0) {
      lines.push("- 추천 업종: " + opp.recommendations.map((r) => r.업종).join(", "));
    }
    lines.push("");
  }

  // Cross result highlights
  const cr = data.cross_result;
  if (cr && cr.length > 0) {
    lines.push("## 매출 추정 요약");
    const topCr = [...cr].sort((a, b) => b.종합_점포당_월매출 - a.종합_점포당_월매출).slice(0, 5);
    topCr.forEach((r) => {
      lines.push(`- ${r.업종}: 점포당 ${formatWon(r.종합_점포당_월매출)} (${r.신뢰등급})`);
    });
    lines.push("");
  }

  return lines.join("\n");
}

export default function ReportPanel() {
  const analysisData = useAnalysisStore((s) => s.analysisData);

  if (!analysisData) {
    return (
      <p className="py-12 text-center text-sm" style={{ color: palette.textSecondary }}>
        리포트 데이터가 없습니다.
      </p>
    );
  }

  const report = generateReport(analysisData);
  const areaName = analysisData.trdar_names?.[0] ?? analysisData.gu_name ?? "상권";

  const handleDownloadPDF = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html><head>
        <meta charset="utf-8">
        <title>${areaName} 상권 분석 리포트</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #1e293b; font-size: 13px; line-height: 1.7; }
          h1 { font-size: 20px; color: #6366F1; border-bottom: 2px solid #6366F1; padding-bottom: 8px; }
          h2 { font-size: 15px; color: #F97316; margin-top: 24px; }
          strong { color: #F97316; }
          li { margin-bottom: 4px; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; text-align: center; }
        </style>
      </head><body>
        ${report.replace(/^# /gm, '<h1>').replace(/^## /gm, '</p><h2>').replace(/^- /gm, '<li>').replace(/\n/g, '<br>')
          .replace(/<h1>(.*?)<br>/g, '<h1>$1</h1>').replace(/<h2>(.*?)<br>/g, '<h2>$1</h2>')
          .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}
        <div class="footer">Generated by 상권분석기 · ${new Date().toLocaleDateString("ko-KR")}</div>
      </body></html>
    `);
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); }, 500);
  };

  return (
    <div className="animate-fade-in">
      {/* 다운로드 버튼 */}
      <button
        onClick={handleDownloadPDF}
        className="mb-3 flex w-full items-center justify-center gap-2 rounded-xl bg-primary-600 py-2.5 text-[13px] font-semibold text-white hover:bg-primary-700 active:scale-[0.98]"
      >
        <Download size={16} /> PDF 리포트 다운로드
      </button>

      <div
        className="prose prose-sm max-w-none rounded-xl border p-4"
        style={{
          borderColor: palette.border,
          background: "white",
          color: palette.textPrimary,
        }}
      >
        <ReactMarkdown
          components={{
            h1: ({ children }) => (
              <h1 className="mb-3 text-lg font-bold" style={{ color: palette.navy }}>
                {children}
              </h1>
            ),
            h2: ({ children }) => (
              <h2 className="mb-2 mt-4 text-base font-bold" style={{ color: palette.orange }}>
                {children}
              </h2>
            ),
            h3: ({ children }) => (
              <h3 className="mb-1 mt-3 text-sm font-semibold" style={{ color: palette.textSecondary }}>
                {children}
              </h3>
            ),
            p: ({ children }) => (
              <p className="mb-2 text-xs leading-relaxed" style={{ color: palette.textPrimary }}>
                {children}
              </p>
            ),
            li: ({ children }) => (
              <li className="text-xs leading-relaxed" style={{ color: palette.textPrimary }}>
                {children}
              </li>
            ),
            strong: ({ children }) => (
              <strong style={{ color: palette.orange }}>{children}</strong>
            ),
          }}
        >
          {report}
        </ReactMarkdown>
      </div>
    </div>
  );
}
